version: '3.8'

services:
  auth-service:
    build:
      context: ./auth-service
    ports:
      - 3001:3000
    environment:
      - DB_URI=${DB_URI}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongodb

  order-service:
    build:
      context: ./order-service
    ports:
      - 3002:3000
    environment:
      - DB_URI=${DB_URI}
    depends_on:
      - mongodb

  product-service:
    build:
      context: ./product-service
    ports:
      - 3003:3000
    environment:
      - DB_URI=${DB_URI}
    depends_on:
      - mongodb

  gateway:
    build:
      context: ./gateway
    ports:
      - 3000:3000
    depends_on:
      - auth-service
      - order-service
      - product-service

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    driver: local
