version: '3.8'

services:
  auth-service:
    build:
      context: ./auth-service
    ports:
      - 3001:3000
    environment:
      - DB_URI=${DB_URI_AUTH}
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  order-service:
    build:
      context: ./order-service
    ports:
      - 3002:3000
    environment:
      - DB_URI=${DB_URI_ORDER}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  product-service:
    build:
      context: ./product-service
    ports:
      - 3003:3000
    environment:
      - DB_URI=${DB_URI_SERVICE}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  gateway:
    build:
      context: ./gateway
    ports:
      - 3000:3000
    depends_on:
      - auth-service
      - order-service
      - product-service

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: redis-server --save 60 1 --loglevel warning
